Replace Nekogram with NekogramX
xuac/warezz pull request #56
Opened 2020-11-26 09:44 UTC by Krusty27

NekogramX is a fork of Nekogram but it is also based on [Telegram-Foss](https://github.com/Telegram-FOSS-Team/Telegram-FOSS), so less dependency on Google Services etc...

2020-12-15 06:32 UTC, xuac requested changes

2020-12-15 06:32 UTC, xuac commented on docs/security.md
> +
```suggestion
- [Librefox](https://librefox.org/) - Firefox with privacy enhancements.
```

why remove LibreFox?

2020-12-20 14:33 UTC, Krusty27 commented on docs/security.md
> +
I moved it from _search engines_ to _browsers_ since it's a browser

2021-01-02 06:38 UTC, xuac commented on docs/security.md
> +
ah sorry didn't catch that 😅

2021-01-02 06:39 UTC, xuac commented
Thanks for updates @Krusty27

2021-01-02 06:39 UTC, merged